### ISSUE TITLE
Where is DeepMirTar.py?

### ISSUE THREAD

**Issue by RenaSch** [Bjoux2/DeepMirTar_SdA#1]
DeepMirTar.py referenced in Usage.docx under DeepMirTar directory (in GoogleDrive) cannot be found.

**Comment by fedevelli** [comment]
Same problem for me. I have contacted the authors but until today I didn't get an answer...

**Comment by Bjoux2** [comment]
@RenaSch @fedevelli Sorry for this problem，I will add the DeepMirTar.py file ASAP.

**Comment by RenaSch** [comment]
Here a little reminder :) @Bjoux2

**Comment by kconge** [comment]
I also need the file, I've been waiting

**Comment by RenaSch** [comment]
Again, please add the file! It is very important for me to get it running.
Thanks :)

**Comment by NKalavros** [comment]
It's weird because your program seems very promising and it is unusable until you actually add this file...

**Comment by Bjoux2** [comment]
@RenaSch @fedevelli @kconge @NKalavros I am really sorry for missing this file. I couldn't find this file after I changed my computer and Operation System. The trained model (SdA.pkl) and other source file are existing, the DeepMirTar.py is a script that combines all the steps to get the final results. I am going to rewrite this file, it will take some time to do it. 
Sorry again, and appreciate your understanding.

**Comment by NKalavros** [comment]
It is A-Ok, we thank you for your great work!

**Comment by NKalavros** [comment]
Hello there Bjoux, I am sorry to ask out of the blue, but was there any progress with the DeepMirTar.py file?

**Comment by NKalavros** [comment]
I hate to be annoying, but I would really appreciate the file itself or guides on how to create it myself, thank you!

**Comment by Bjoux2** [comment]
@NKalavros I appreciate your reminder. Before reinstalling my computer system I need to finish the work which I am doing now, it will be finished in a few days. After that, I will reinstall the Linux system and then write the DeepMirTar.py file. I'm very sorry for the delay and inconvenience.

**Comment by NKalavros** [comment]
Hello once more Bjoux, has there been any progress with the file? Thank you very much.

**Comment by Bjoux2** [comment]
Hi @NKalavros , the DeepMirTar.py is uploaded, you can download at the Google Driver, if you have any other questions, please feel free to contact me. 
Sorry for the late, and thanks for your reminder.
